import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/assets/styles/globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="bg-foreground p-4 text-lg">
          <div className="container mx-auto flex justify-between gap-4">
            <span className="flex-1 max-[475px]:hidden">logo</span>
            <span className="flex-1 flex justify-center gap-4">
              <Link href="/">Program</Link>
              <Link href="/full">Min side</Link>
            </span>
            <span className="flex-1 max-[475px]:hidden text-end">Fornavn Etternavn</span>
          </div>
        </header>
        <div className="container mx-auto flex justify-between p-4 text-sm">
          <p className="max-[475px]:hidden">Home / Event title</p>
          <span className="flex gap-4">
            <p>Forrige</p>
            <b>Neste</b>
          </span>
        </div>
        {children}
      </body>
    </html>
  );
}
